language: node_js
node_js:
 - 5.6.0
notifications:
 - rpeleias@hotmail.com
script:
 - npm run apidoc
 - npm test
deploy:
  provider: heroku
  api_key: d98bd741-0697-41e7-b617-4f0ca8476727
  app: vast-refuge-66648